language: rust
rust:
  - nightly
  - beta
  - stable
before_install:
  - sudo add-apt-repository ppa:webkit-team/ppa -y
  - sudo apt-get update
  - sudo apt-get install libwebkit2gtk-4.0-dev -y
addons:
  apt:
    packages:
    - libgtk-3-dev
script:
  - rustc --version
  - ./check_init_asserts
  - cargo build --all-features
