[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "webkit2gtk-webextension"
version = "0.1.0"

[dependencies]
glib = "^0.1.3"
glib-sys = "^0.3.4"
gobject-sys = "^0.3.4"
gtk = "^0.1.3"
libc = "^0.2"

[dependencies.webkit2gtk-webextension-sys]
git = "https://github.com/antoyo/webkit2gtk-webextension-sys-rs"
branch = "crate"
version = "^0.2"

[features]
v2_10 = ["v2_8", "webkit2gtk-webextension-sys/v2_10"]
v2_12 = ["v2_10", "webkit2gtk-webextension-sys/v2_12"]
v2_2 = ["webkit2gtk-webextension-sys/v2_2"]
v2_8 = ["v2_2", "webkit2gtk-webextension-sys/v2_8"]
