[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "0.9"
glib-sys = "^0.3.4"
gobject-sys = "^0.3.4"
gtk = "^0.1.3"
gtk-sys = "^0.3.4"
libc = "0.2"

# TODO: switch to the version published on crates.io
[dependencies.javascriptcore-sys]
git = "https://github.com/antoyo/javascriptcore-sys-rs"

# TODO: switch to the version published on crates.io
[dependencies.soup-sys]
branch = "crate"
git = "https://github.com/antoyo/soup-sys-rs"

[features]
v2_10 = ["v2_8"]
v2_12 = ["v2_10"]
v2_14 = ["v2_12"]
v2_16 = ["v2_14"]
v2_6 = []
v2_8 = ["v2_6"]

[lib]
name = "webkit2gtk_webextension_sys"

[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
build = "build.rs"
links = "web_kit2_web_extension"
name = "webkit2gtk-webextension-sys"
version = "0.2.0"
